# Generated by Django 5.0.3 on 2024-03-29 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Novel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("novel_id", models.CharField(max_length=13, unique=True)),
                ("title", models.CharField(max_length=30)),
                ("body", models.TextField(max_length=300)),
                ("summary", models.CharField(max_length=60)),
                (
                    "document",
                    models.FileField(
                        help_text="Upload PDF document", upload_to="novels/"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="novels",
                        to="users.author",
                    ),
                ),
                ("categories", models.ManyToManyField(to="novels.category")),
            ],
        ),
    ]
